# Generated by Django 4.0.4 on 2022-04-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_complain_scope_alter_complain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='person',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
